name: speaker_diarization
description: >
  This example demonstrates how to use the Dart API for speaker diarization.

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  sherpa_onnx: ^1.12.15
  # sherpa_onnx:
  #   path: ../../flutter/sherpa_onnx
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
