name: streaming_asr

description: >
  This example shows how to implement real-time speech recognition using sherpa-onnx.

publish_to: 'none'

version: 1.10.22

topics:
  - speech-recognition

issue_tracker: https://github.com/k2-fsa/sherpa-onnx/issues

repository: https://github.com/k2-fsa/sherpa-onnx/tree/master/sherpa-onnx/flutter

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  path_provider: ^2.1.3
  path: ^1.9.0

  # Note: record does not support Linux for streaming ASR
  record: ^5.1.0
  url_launcher: ^6.2.6

  sherpa_onnx: ^1.10.22
  # sherpa_onnx:
    # path: ../../flutter/sherpa_onnx

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/
