name: tts
description: >
  This example shows how to implement text to speech, i.e., speech synthesis,
  using sherpa-onnx.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.12.15

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  path: ^1.9.0
  sherpa_onnx: ^1.12.15
  # sherpa_onnx:
  #   path: ../../flutter/sherpa_onnx
  url_launcher: 6.2.6
  url_launcher_linux: 3.1.0
  audioplayers: ^5.0.0
  media_kit: 
  media_kit_libs_video: 

flutter:
  uses-material-design: true

  assets:
    - assets/vits-melo-tts-zh_en/
    - assets/vits-melo-tts-zh_en/dict/