name: audio_tagging

description: >
  This example demonstrates how to use the Dart API for audio tagging.

version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  sherpa_onnx: ^1.10.19
  path: ^1.9.0
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
