name: sherpa_onnx

description: >
  Speech recognition, speech synthesis, and speaker recognition using next-gen Kaldi
  with onnxruntime without Internet connection.

repository: https://github.com/k2-fsa/sherpa-onnx/tree/master/sherpa-onnx/flutter

issue_tracker: https://github.com/k2-fsa/sherpa-onnx/issues
documentation: https://k2-fsa.github.io/sherpa/onnx/

topics:
  - speech-recognition
  - speech-synthesis
  - speaker-identification
  - audio-tagging
  - voice-activity-detection

# remember to change the version in macos/sherpa_onnx.podspec
version: 0.0.2

homepage: https://github.com/k2-fsa/sherpa-onnx

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
