name: sherpa_onnx

description: >
  Speech recognition, speech synthesis, speaker diarization, and speaker recognition
  using next-gen Kaldi with onnxruntime without Internet connection.

repository: https://github.com/k2-fsa/sherpa-onnx/tree/master/flutter

issue_tracker: https://github.com/k2-fsa/sherpa-onnx/issues
documentation: https://k2-fsa.github.io/sherpa/onnx/

topics:
  - speech-recognition
  - speech-synthesis
  - speaker-diarization
  - audio-tagging
  - voice-activity-detection

# remember to change the version in ../sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec
version: 1.12.15

homepage: https://github.com/k2-fsa/sherpa-onnx

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

  sherpa_onnx_android: ^1.12.15
  # sherpa_onnx_android:
  #   path: ../sherpa_onnx_android

  sherpa_onnx_macos: ^1.12.15
  # sherpa_onnx_macos:
  #   path: ../sherpa_onnx_macos

  sherpa_onnx_linux: ^1.12.15
  # sherpa_onnx_linux:
  #   path: ../sherpa_onnx_linux

  sherpa_onnx_windows: ^1.12.15
  # sherpa_onnx_windows:
  #   path: ../sherpa_onnx_windows

  sherpa_onnx_ios: ^1.12.15
  # sherpa_onnx_ios:
  #   path: ../sherpa_onnx_ios

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: sherpa_onnx_android

      ios:
        default_package: sherpa_onnx_ios

      macos:
        default_package: sherpa_onnx_macos

      linux:
        default_package: sherpa_onnx_linux

      windows:
        default_package: sherpa_onnx_windows
