name: android-rknn

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/android-rknn.yaml'
      - 'cmake/**'
      - 'sherpa-onnx/csrc/*'
      - 'sherpa-onnx/jni/*'
      - 'build-android*.sh'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

concurrency:
  group: android-rknn-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android-rknn-libs:
    name: Android rknn libs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-android-rknn

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: Display NDK HOME
        shell: bash
        run: |
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"
          ls -lh ${ANDROID_NDK_LATEST_HOME}

      - name: build android arm64-v8a
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
          export SHERPA_ONNX_ENABLE_C_API=ON
          export SHERPA_ONNX_ENABLE_RKNN=ON
          ./build-android-arm64-v8a.sh
          mkdir -p jniLibs/arm64-v8a/
          cp -v ./build-android-arm64-v8a/install/lib/*.so ./jniLibs/arm64-v8a/
          cp -v ./build-android-arm64-v8a/install/lib/README.md ./jniLibs/arm64-v8a/
          rm -rf  ./build-android-arm64-v8a/

      - name: build android armv7-eabi
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
          export SHERPA_ONNX_ENABLE_C_API=ON
          export SHERPA_ONNX_ENABLE_RKNN=ON
          ./build-android-armv7-eabi.sh
          mkdir -p ./jniLibs/armeabi-v7a/
          cp -v ./build-android-armv7-eabi/install/lib/*.so ./jniLibs/armeabi-v7a/
          cp -v ./build-android-armv7-eabi/install/lib/README.md ./jniLibs/armeabi-v7a/
          rm -rf ./build-android-armv7-eabi

      - name: Copy files
        shell: bash
        run: |
          SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
          echo "SHERPA_ONNX_VERSION=$SHERPA_ONNX_VERSION" >> "$GITHUB_ENV"

          filename=sherpa-onnx-${SHERPA_ONNX_VERSION}-android-rknn.tar.bz2

          tar cjvf $filename ./jniLibs

          ls -lh

      - uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-android-libs-rknn
          path: ./jniLibs

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"
            du -h -d1 .
            ls -lh

            rm -rf huggingface
            export GIT_CLONE_PROTECTION_ACTIVE=false
            GIT_LFS_SKIP_SMUDGE=1 git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/sherpa-onnx-libs huggingface

            cd huggingface

            cp -v ../sherpa-onnx-*-android-rknn.tar.bz2 ./

            git status
            git lfs track "*.bz2"

            git add .

            git commit -m "upload sherpa-onnx-${SHERPA_ONNX_VERSION}-android.tar.bz2"

            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/sherpa-onnx-libs main

      - name: Release android libs
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: sherpa-onnx-*-android-rknn.tar.bz2
          # repo_name: k2-fsa/sherpa-onnx
          # repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          # tag: v1.12.13

  build-android-aar-rknn:
    needs: [build-android-rknn-libs]
    name: Android rknn AAR
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Display NDK HOME
        shell: bash
        run: |
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"
          ls -lh ${ANDROID_NDK_LATEST_HOME}

      - name: Retrieve artifact
        uses: actions/download-artifact@v4
        with:
          name: sherpa-onnx-android-libs-rknn
          path: /tmp/jniLibs

      - name: Show jni libs
        shell: bash
        run: |
          ls -lh /tmp/jniLibs

          # drwxr-xr-x 2 runner docker 4.0K Dec 12 06:56 arm64-v8a
          # drwxr-xr-x 2 runner docker 4.0K Dec 12 06:56 armeabi-v7a

      - name: Copy libs
        shell: bash
        run: |
          for arch in arm64-v8a armeabi-v7a; do
            cp -v /tmp/jniLibs/$arch/* android/SherpaOnnxAar/sherpa_onnx/src/main/jniLibs/$arch/
          done

          rm -rf android/SherpaOnnxAar/sherpa_onnx/src/main/jniLibs/x86
          rm -rf android/SherpaOnnxAar/sherpa_onnx/src/main/jniLibs/x86_64

      - name: Check libs
        shell: bash
        run: |
          ls -lh android/SherpaOnnxAar/sherpa_onnx/src/main/jniLibs/*

      - name: Build aar
        shell: bash
        run: |
          cd android/SherpaOnnxAar

          ./gradlew :sherpa_onnx:assembleRelease

      - name: Display aar
        shell: bash
        run: |
          cd android/SherpaOnnxAar

          ls -lh ./sherpa_onnx/build/outputs/aar/sherpa_onnx-release.aar
          cp ./sherpa_onnx/build/outputs/aar/sherpa_onnx-release.aar ../../


      - name: Rename aar
        shell: bash
        run: |
          SHERPA_ONNX_VERSION=$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
          echo "SHERPA_ONNX_VERSION=$SHERPA_ONNX_VERSION" >> "$GITHUB_ENV"

          mv sherpa_onnx-release.aar sherpa-onnx-${SHERPA_ONNX_VERSION}-rknn.aar

      - uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-android-aar
          path: ./*.aar

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"
            du -h -d1 .
            ls -lh

            rm -rf huggingface
            export GIT_CLONE_PROTECTION_ACTIVE=false
            GIT_LFS_SKIP_SMUDGE=1 git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/sherpa-onnx-libs huggingface

            cd huggingface
            dst=android/aar
            mkdir -p $dst

            cp -v ../*.aar $dst

            git status
            git lfs track "*.aar"

            git add .

            git commit -m "upload sherpa-onnx-${SHERPA_ONNX_VERSION}-rknn.aar"

            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/sherpa-onnx-libs main

      - name: Release android aar
        if: github.repository_owner == 'csukuangfj' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./*.aar
          # repo_name: k2-fsa/sherpa-onnx
          # repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          # tag: v1.12.13

      - name: Release android aar
        if: github.repository_owner == 'k2-fsa' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./*.aar
