name: apk

on:
  push:
    branches:
      - apk
    tags:
      - '*'

  workflow_dispatch:

concurrency:
  group: apk-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  apk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Display NDK HOME
        shell: bash
        run: |
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"
          ls -lh ${ANDROID_NDK_LATEST_HOME}

      - name: build APK
        shell: bash
        run: |
          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
          ./build-apk-two-pass.sh
          ./build-apk.sh

      - name: Display APK
        shell: bash
        run: |
          ls -lh ./apks/

      - uses: actions/upload-artifact@v2
        with:
          path: ./apks/*.apk

      - name: Release APK
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: apks/*.apk
