name: export-omnilingual-asr-to-onnx

on:
  push:
    branches:
      - omnilingual-1b
  workflow_dispatch:

concurrency:
  group: export-omnilingual-asr-to-onnx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-omnilingual-asr-to-onnx:
    if: github.repository_owner == 'k2-fsa' || github.repository_owner == 'csukuangfj'
    name: ${{ matrix.model_card }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        model_card: ["omniASR_CTC_300M", "omniASR_CTC_300M_v2", "omniASR_CTC_1B", "omniASR_CTC_1B_v2"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt install libsndfile1

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install fairseq2 \
            --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/pt2.8.0/cpu \
            torch==2.8.0+cpu -f https://download.pytorch.org/whl/torch \
            torchaudio==2.8.0+cpu -f https://download.pytorch.org/whl/torchaudio \
            onnx==1.17.0 \
            onnxruntime==1.17.1 \
            soundfile \
            librosa

          pip install --no-deps omnilingual_asr

          pip install retrying pandas polars pyarrow xxhash

      - name: Setup tmate session
        if: false
        uses: mxschmitt/action-tmate@v3

      - name: Run
        shell: bash
        run: |
          cd scripts/omnilingual-asr
          model_card=${{ matrix.model_card }}
          python3 ./export-onnx.py --model-card $model_card

          ls -lh *.onnx
          ls -lh *.weights || true

          rm README.md

          curl -SL -O https://raw.githubusercontent.com/facebookresearch/omnilingual-asr/refs/heads/main/README.md
          curl -SL -O https://raw.githubusercontent.com/facebookresearch/omnilingual-asr/refs/heads/main/LICENSE

          curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/en.wav
          curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/es.wav
          curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/fr.wav
          curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/de.wav

          echo "---test----"
          python3 ./test.py

          echo "---collect files----"

          if [[ $model_card == omniASR_CTC_300M ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-2025-11-12
          elif [[ $model_card == omniASR_CTC_300M_v2 ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-v2-2026-02-05
          elif [[ $model_card == omniASR_CTC_1B ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-2025-11-12
          elif [[ $model_card == omniASR_CTC_1B_v2 ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-v2-2026-02-05
          else
            echo "Unknown model: $model_card"
            exit 1
          fi

          mkdir -p $d
          mkdir -p $d/test_wavs

          mv -v model.onnx $d
          mv -v model.weights $d || true
          cp -v tokens.txt $d
          cp -v README.md $d
          cp -v LICENSE* $d
          cp -v *.wav $d/test_wavs

          ls -lh $d

          tar cjfv $d.tar.bz2 $d
          mv $d ../..

          if [[ $model_card == omniASR_CTC_300M ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12
          elif [[ $model_card == omniASR_CTC_300M_v2 ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-v2-int8-2026-02-05
          elif [[ $model_card == omniASR_CTC_1B ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-int8-2025-11-12
          elif [[ $model_card == omniASR_CTC_1B_v2 ]]; then
            d=sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-v2-int8-2026-02-05
          else
            echo "Unknown model: $model_card"
            exit 1
          fi

          mkdir -p $d
          mkdir -p $d/test_wavs

          mv -v model.int8.onnx $d
          cp -v tokens.txt $d
          cp -v README.md $d
          cp -v LICENSE* $d
          cp -v *.wav $d/test_wavs
          ls -lh $d

          tar cjfv $d.tar.bz2 $d

          mv $d ../..

          mv *.tar.bz2 ../../

          cd ../..

          ls -lh *.tar.bz2

          df -h
          rm -fv onnx_* model.encoder* model.final*

          ls -lh ~/.cache/fairseq2/assets/*

          rm -rf ~/.cache/fairseq2/assets/
          rm -rf ~/.cache

          df -h

      - name: Publish to huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false

            model_card=${{ matrix.model_card }}

            dirs=(
              sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-2025-11-12
              sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12
              sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-v2-2026-02-05
              sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-v2-int8-2026-02-05
              sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-2025-11-12
              sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-int8-2025-11-12
              sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-v2-2026-02-05
              sherpa-onnx-omnilingual-asr-1600-languages-1B-ctc-v2-int8-2026-02-05
            )

            for d in ${dirs[@]}; do
              if [[ ! -d $d ]]; then
                continue;
              fi
              rm -rf huggingface
              git clone https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/$d huggingface
              pushd huggingface

              git fetch
              git pull
              echo "pwd: $PWD"
              rm -fv ./*.weights
              mv -v ../$d/* .

              git lfs track "*.onnx"
              git lfs track "*.weights"
              git lfs track "*.wav"
              ls -lh
              git add .

              ls -lh

              git status

              git commit -m "add models"
              git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/$d main || true
              popd
            done

      - name: Publish to modelscope
        if: true
        env:
          MS_TOKEN: ${{ secrets.MODEL_SCOPE_GIT_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"
            for m in *.tar.bz2; do
              export GIT_LFS_SKIP_SMUDGE=1
              export GIT_CLONE_PROTECTION_ACTIVE=false

              rm -rf ms
              git clone https://oauth2:${MS_TOKEN}@www.modelscope.cn/csukuangfj/asr-models.git ms

              cp -av $m ms/

              pushd ms
              git lfs track "*.tar.bz2"
              git status
              ls -lh
              git add .

              git commit -m "add models"
              git push https://oauth2:${MS_TOKEN}@www.modelscope.cn/csukuangfj/asr-models.git

              popd
            done

      # List large files first (safe)
      - name: List .tar.bz2 files larger than 2GB
        run: |
          ls -lh *.tar.bz2
          echo "----"
          find . -type f -name "*.tar.bz2" -size +2G -print

      # Delete large files
      - name: Delete .tar.bz2 files larger than 2GB
        run: |
          find . -type f -name "*.tar.bz2" -size +2G -delete

          ls -lh *.tar.bz2

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models
