name: export-moonshine-to-onnx

on:
  push:
    branches:
      - export-moonshine-v2-2
  workflow_dispatch:

concurrency:
  group: export-moonshine-to-onnx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-moonshine-to-onnx:
    if: github.repository_owner == 'k2-fsa' || github.repository_owner == 'csukuangfj'
    name: export moonshine ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.10"]
        version: [v2]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install -q onnx onnxruntime librosa tokenizers soundfile moonshine-voice

      - name: Run v1
        if: matrix.version == 'v1'
        shell: bash
        run: |
          pushd scripts/moonshine
          ./run.sh
          popd

          mv -v scripts/moonshine/*.tar.bz2 .
          mv -v scripts/moonshine/sherpa-onnx-* ./

      - name: Run v2
        if: matrix.version == 'v2'
        shell: bash
        run: |
          pushd scripts/moonshine/v2
          ./run.sh
          popd

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models

      - name: Publish to huggingface
        if: true
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"
            models=(
              sherpa-onnx-moonshine-tiny-en-int8
              sherpa-onnx-moonshine-base-en-int8
              sherpa-onnx-moonshine-base-ar-quantized-2026-02-27
              sherpa-onnx-moonshine-base-en-quantized-2026-02-27
              sherpa-onnx-moonshine-base-es-quantized-2026-02-27
              sherpa-onnx-moonshine-base-ja-quantized-2026-02-27
              sherpa-onnx-moonshine-base-zh-quantized-2026-02-27
              sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27
              sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27
            )
            for d in ${models[@]}; do
              if [ ! -d $d ]; then
                continue;
              fi

              export GIT_LFS_SKIP_SMUDGE=1
              export GIT_CLONE_PROTECTION_ACTIVE=false
              rm -rf huggingface
              git clone https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/$d huggingface

              rm -rf huggingface/*.onnx
              rm -rf huggingface/*/*.wav

              cp -av $d/* huggingface

              pushd huggingface
              git lfs track "*.onnx"
              git lfs track "*.ort"
              git lfs track "*.data"
              git lfs track "*.weights"
              git lfs track "bpe.model"
              git lfs track "*.wav"
              git lfs track "*.json"
              git status
              git add .

              git commit -m "add models"
              git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/$d main

              popd
            done

            rm -rf huggingface

      - name: Publish to modelscope
        if: true
        env:
          MS_TOKEN: ${{ secrets.MODEL_SCOPE_GIT_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"
            for m in *.tar.bz2; do
              export GIT_LFS_SKIP_SMUDGE=1
              export GIT_CLONE_PROTECTION_ACTIVE=false

              rm -rf ms
              git clone https://oauth2:${MS_TOKEN}@www.modelscope.cn/csukuangfj/asr-models.git ms

              cp -av $m ms/

              pushd ms
              git lfs track "*.tar.bz2"
              git status
              ls -lh
              git add .

              git commit -m "add models"
              git push https://oauth2:${MS_TOKEN}@www.modelscope.cn/csukuangfj/asr-models.git

              popd
            done

            rm -rf ms
