name: export-nemo-giga-am-to-onnx

on:
  push:
    branches:
      - export-giga-am-v3
  workflow_dispatch:

concurrency:
  group: export-nemo-giga-am-to-onnx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-nemo-am-giga-to-onnx:
    if: github.repository_owner == 'k2-fsa' || github.repository_owner == 'csukuangfj'
    name: export nemo GigaAM models to ONNX
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run CTC
        if: false
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-ctc.sh
          popd

          d=sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24
          mkdir $d
          mkdir $d/test_wavs
          rm scripts/nemo/GigaAM/model.onnx
          mv -v scripts/nemo/GigaAM/*.int8.onnx $d/
          cp -v scripts/nemo/GigaAM/*.md $d/
          mv -v scripts/nemo/GigaAM/*.pdf $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-ctc.sh $d/
          mv -v scripts/nemo/GigaAM/export-onnx-ctc.py $d/
          cp -v scripts/nemo/GigaAM/test-onnx-ctc.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

      - name: Run Transducer
        if: false
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-rnnt.sh
          popd

          d=sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24
          mkdir $d
          mkdir $d/test_wavs

          mv -v scripts/nemo/GigaAM/encoder.int8.onnx $d/
          mv -v scripts/nemo/GigaAM/decoder.onnx $d/
          mv -v scripts/nemo/GigaAM/joiner.onnx $d/

          cp -v scripts/nemo/GigaAM/*.md $d/
          mv -v scripts/nemo/GigaAM/*.pdf $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-rnnt.sh $d/
          mv -v scripts/nemo/GigaAM/export-onnx-rnnt.py $d/
          cp -v scripts/nemo/GigaAM/test-onnx-rnnt.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

      - name: Run CTC v2
        if: false
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-ctc-v2.sh
          popd

          d=sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19
          mkdir $d
          mkdir $d/test_wavs
          rm scripts/nemo/GigaAM/v2_ctc.onnx
          mv -v scripts/nemo/GigaAM/*.int8.onnx $d/
          cp -v scripts/nemo/GigaAM/LICENSE $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-ctc-v2.sh $d/
          mv -v scripts/nemo/GigaAM/*-ctc-v2.py $d/
          cp -v scripts/nemo/GigaAM/test-onnx-ctc.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

      - name: Run Transducer v2
        if: false
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-rnnt-v2.sh
          popd

          d=sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19
          mkdir $d
          mkdir $d/test_wavs

          mv -v scripts/nemo/GigaAM/encoder.int8.onnx $d/
          mv -v scripts/nemo/GigaAM/decoder.onnx $d/
          mv -v scripts/nemo/GigaAM/joiner.onnx $d/

          cp -v scripts/nemo/GigaAM/*.md $d/
          cp -v scripts/nemo/GigaAM/LICENSE $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-rnnt-v2.sh $d/
          cp -v scripts/nemo/GigaAM/test-onnx-rnnt.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

      - name: Run CTC v3
        if: false
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-ctc-v3.sh
          popd

          d=sherpa-onnx-nemo-ctc-giga-am-v3-russian-2025-12-16
          mkdir $d
          mkdir $d/test_wavs
          ls -lh scripts/nemo/GigaAM/v3_ctc.onnx
          rm scripts/nemo/GigaAM/v3_ctc.onnx
          mv -v scripts/nemo/GigaAM/*.int8.onnx $d/
          cp -v scripts/nemo/GigaAM/LICENSE $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-ctc-v3.sh $d/
          mv -v scripts/nemo/GigaAM/*-ctc-v3.py $d/
          cp -v scripts/nemo/GigaAM/test-onnx-ctc.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

          ls -lh *.tar.bz2

      - name: Run CTC v3 with punctuations
        if: false
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-ctc-v3-punct.sh
          popd

          d=sherpa-onnx-nemo-ctc-punct-giga-am-v3-russian-2025-12-16
          mkdir $d
          mkdir $d/test_wavs
          rm scripts/nemo/GigaAM/v3_e2e_ctc.onnx
          mv -v scripts/nemo/GigaAM/*.int8.onnx $d/
          cp -v scripts/nemo/GigaAM/LICENSE $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-ctc-v3-punct.sh $d/
          mv -v scripts/nemo/GigaAM/*-ctc-v3-punct.py $d/
          cp -v scripts/nemo/GigaAM/test-onnx-ctc.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

          ls -lh *.tar.bz2

      - name: Run Transducer v3
        if: true
        shell: bash
        run: |
          pushd scripts/nemo/GigaAM
          ./run-rnnt-v3.sh
          popd

          d=sherpa-onnx-nemo-transducer-giga-am-v3-russian-2025-12-16
          mkdir $d
          mkdir $d/test_wavs

          mv -v scripts/nemo/GigaAM/encoder.int8.onnx $d/
          mv -v scripts/nemo/GigaAM/decoder.onnx $d/
          mv -v scripts/nemo/GigaAM/joiner.onnx $d/

          cp -v scripts/nemo/GigaAM/*.md $d/
          cp -v scripts/nemo/GigaAM/LICENSE $d/
          mv -v scripts/nemo/GigaAM/tokens.txt $d/
          mv -v scripts/nemo/GigaAM/*.wav $d/test_wavs/
          mv -v scripts/nemo/GigaAM/run-rnnt-v3.sh $d/
          cp -v scripts/nemo/GigaAM/test-onnx-rnnt.py $d/

          ls -lh scripts/nemo/GigaAM/

          ls -lh $d

          tar cjvf ${d}.tar.bz2 $d

      - name: Release
        if: github.repository_owner == 'csukuangfj'
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models

      - name: Release
        if: github.repository_owner == 'k2-fsa'
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          tag: asr-models

      - name: Publish to huggingface (CTC)
        if: false
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            d=sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24/
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false
            rm -rf huggingface
            git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d huggingface
            cp -av $d/* ./huggingface
            cd huggingface
            git lfs track "*.onnx"
            git lfs track "*.wav"
            git status
            git add .
            git status
            git commit -m "add models"
            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d main

      - name: Publish to huggingface (Transducer)
        if: false
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            d=sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false
            rm -rf huggingface
            git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d huggingface
            cp -av $d/* ./huggingface
            cd huggingface
            git lfs track "*.onnx"
            git lfs track "*.wav"
            git status
            git add .
            git status
            git commit -m "add models"
            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d main

      - name: Publish v2 to huggingface (CTC)
        if: false
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            d=sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19/
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false
            rm -rf huggingface
            git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d huggingface
            cp -av $d/* ./huggingface
            cd huggingface
            git lfs track "*.onnx"
            git lfs track "*.wav"
            git status
            git add .
            git status
            git commit -m "add models"
            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d main

      - name: Publish v2 to huggingface (Transducer)
        if: false
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            d=sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false
            rm -rf huggingface
            git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d huggingface
            cp -av $d/* ./huggingface
            cd huggingface
            git lfs track "*.onnx"
            git lfs track "*.wav"
            git status
            git add .
            git status
            git commit -m "add models"
            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d main

      - name: Publish v3 to huggingface
        if: true
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            names=(
             sherpa-onnx-nemo-ctc-giga-am-v3-russian-2025-12-16
             sherpa-onnx-nemo-ctc-punct-giga-am-v3-russian-2025-12-16
             sherpa-onnx-nemo-transducer-giga-am-v3-russian-2025-12-16
            )
            for d in ${names[@]}; do
              if [ ! -d $d ]; then
                echo "$d does not exist - skip it"
                continue;
              fi

              export GIT_LFS_SKIP_SMUDGE=1
              export GIT_CLONE_PROTECTION_ACTIVE=false
              rm -rf huggingface
              git clone https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d huggingface
              cp -av $d/* ./huggingface
              cd huggingface
              git lfs track "*.onnx"
              git lfs track "*.wav"
              git status
              git add .
              git status
              git commit -m "add models"
              git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$d main
              cd ..
            done
