name: export-nemo-speaker-verification-to-onnx

on:
  workflow_dispatch:

concurrency:
  group: export-nemo-fast-conformer-hybrid-transducer-ctc-to-onnx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-nemo-fast-conformer-hybrid-transducer-ctc-to-onnx:
    if: github.repository_owner == 'k2-fsa' || github.repository_owner == 'csukuangfj'
    name: export NeMo fast conformer
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install NeMo
        shell: bash
        run: |
          BRANCH='main'
          pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[asr]
          pip install onnxruntime
          pip install kaldi-native-fbank
          pip install soundfile librosa

      - name: Run
        shell: bash
        run: |
          cd scripts/nemo/fast-conformer-hybrid-transducer-ctc
          ./run-ctc.sh

          mv -v sherpa-onnx-nemo* ../../..

      - name: Download test waves
        shell: bash
        run: |
          mkdir test_wavs
          pushd test_wavs
          curl -SL -O https://hf-mirror.com/csukuangfj/sherpa-onnx-nemo-ctc-en-conformer-small/resolve/main/test_wavs/0.wav
          curl -SL -O https://hf-mirror.com/csukuangfj/sherpa-onnx-nemo-ctc-en-conformer-small/resolve/main/test_wavs/1.wav
          curl -SL -O https://hf-mirror.com/csukuangfj/sherpa-onnx-nemo-ctc-en-conformer-small/resolve/main/test_wavs/8k.wav
          curl -SL -O https://hf-mirror.com/csukuangfj/sherpa-onnx-nemo-ctc-en-conformer-small/resolve/main/test_wavs/trans.txt
          popd

          cp -av test_wavs ./sherpa-onnx-nemo-streaming-fast-conformer-ctc-80ms
          cp -av test_wavs ./sherpa-onnx-nemo-streaming-fast-conformer-ctc-480ms
          cp -av test_wavs ./sherpa-onnx-nemo-streaming-fast-conformer-ctc-1040ms

          tar cjvf sherpa-onnx-nemo-streaming-fast-conformer-ctc-80ms.tar.bz2 sherpa-onnx-nemo-streaming-fast-conformer-ctc-80ms
          tar cjvf sherpa-onnx-nemo-streaming-fast-conformer-ctc-480ms.tar.bz2 sherpa-onnx-nemo-streaming-fast-conformer-ctc-480ms
          tar cjvf sherpa-onnx-nemo-streaming-fast-conformer-ctc-1040ms.tar.bz2 sherpa-onnx-nemo-streaming-fast-conformer-ctc-1040ms

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models
