name: riscv64-spacemit-linux

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/riscv64-spacemit-linux.yaml'
      - 'cmake/**'
      - 'sherpa-onnx/csrc/*'
      - 'sherpa-onnx/c-api/*'
      - 'toolchains/riscv64-linux-gnu-spacemit.toolchain.cmake'
      - 'build-riscv64-linux-gnu-spacemit.sh'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

concurrency:
  group: riscv64-spacemit-linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  riscv64_spacemit_linux:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.lib_type }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        lib_type: [shared] #, static]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-riscv64-spacemit-${{ matrix.lib_type }}

      - name: cache-qemu
        id: cache-qemu
        uses: actions/cache@v4
        with:
          path: qemu-install
          key: qemu-riscv-spacemit-install-20250818

      - name: qemu
        if: steps.cache-qemu.outputs.cache-hit != 'true'
        run: |
          wget -q https://archive.spacemit.com/spacemit-ai/qemu/jdsk-qemu-v10.0.2.tar.gz
          tar -xf jdsk-qemu-v10.0.2.tar.gz
          mkdir -p qemu-install/bin

          cp -v ./jdsk-qemu/bin/qemu-riscv64 ./qemu-install/bin

      - name: cache-toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: toolchain
          key: https://archive.spacemit.com/toolchain/spacemit-toolchain-linux-glibc-x86_64-v1.1.2.tar.xz

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        shell: bash
        run: |
          wget -q https://archive.spacemit.com/toolchain/spacemit-toolchain-linux-glibc-x86_64-v1.1.2.tar.xz

          mkdir $GITHUB_WORKSPACE/toolchain

          tar xvf spacemit-toolchain-linux-glibc-x86_64-v1.1.2.tar.xz --strip-components 1 -C $GITHUB_WORKSPACE/toolchain
          ls -lh $GITHUB_WORKSPACE/toolchain/bin

      - name: Display toolchain info
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          riscv64-unknown-linux-gnu-gcc --version

      - name: Display qemu-riscv64 -h
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
          export QEMU_LD_PREFIX=$GITHUB_WORKSPACE/toolchain/sysroot
          qemu-riscv64 -h

      - name: build riscv64-spacemit-linux
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH

          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

          cmake --version

          lib_type=${{ matrix.lib_type }}

          if [[ $lib_type == "shared" ]]; then
            export BUILD_SHARED_LIBS=ON
          else
            export BUILD_SHARED_LIBS=OFF
          fi

          export RISCV_ROOT_PATH=$GITHUB_WORKSPACE/toolchain
          ./build-riscv64-linux-gnu-spacemit.sh

          ls -lh build-riscv64-linux-gnu-spacemit/bin
          ls -lh build-riscv64-linux-gnu-spacemit/lib

          echo "---install/lib---"
          ls -lh build-riscv64-linux-gnu-spacemit/install/lib

          echo "---install/bin---"
          ls -lh build-riscv64-linux-gnu-spacemit/install/bin

          file build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx

          readelf -d build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx

      - name: Copy files
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          riscv64-unknown-linux-gnu-strip --version

          SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)

          dst=sherpa-onnx-${SHERPA_ONNX_VERSION}-linux-riscv64-spacemit-${{ matrix.lib_type }}
          mkdir $dst

          cp -v $GITHUB_WORKSPACE/toolchain/sysroot/lib/ld-linux-riscv64-lp64d.so.1 build-riscv64-linux-gnu-spacemit/install/lib/

          ls -lh build-riscv64-linux-gnu-spacemit/install/lib

          cp -a build-riscv64-linux-gnu-spacemit/install/bin $dst/
          ls -lh $dst/bin/*
          riscv64-unknown-linux-gnu-strip $dst/bin/*
          ls -lh $dst

          lib_type=${{ matrix.lib_type }}
          if [[ $lib_type == "shared" ]]; then
            cp -a build-riscv64-linux-gnu-spacemit/install/lib $dst/
            rm -fv $dst/lib/libasound.so
          fi

          tree $dst

          tar cjvf ${dst}.tar.bz2 $dst

      - uses: actions/upload-artifact@v4
        if: matrix.lib_type == 'shared'
        with:
          name: sherpa-onnx-linux-riscv64-spacemit-shared
          path: sherpa-onnx-*linux-riscv64-spacemit-shared.tar.bz2

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            SHERPA_ONNX_VERSION=$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_CLONE_PROTECTION_ACTIVE=false

            GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/sherpa-onnx-libs huggingface

            cd huggingface
            dst=riscv64-spacemit/$SHERPA_ONNX_VERSION
            mkdir -p $dst

            cp -v ../sherpa-onnx-*-shared.tar.bz2 $dst/

            git status
            git lfs track "*.bz2"

            git add .

            git commit -m "upload sherpa-onnx-${SHERPA_ONNX_VERSION}-linux-riscv64-spacemit-shared.tar.bz2"

            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/sherpa-onnx-libs main

      - uses: actions/upload-artifact@v4
        if: matrix.lib_type == 'static'
        with:
          name: sherpa-onnx-linux-riscv64-spacemit-static
          path: sherpa-onnx-*linux-riscv64-spacemit-static.tar.bz2

      - name: Release pre-compiled binaries and libs for riscv64 linux ${{ matrix.lib_type }}
        if: github.repository_owner == 'csukuangfj' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: sherpa-onnx-*linux-riscv64*.tar.bz2
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: v1.12.11

      - name: Release pre-compiled binaries and libs for riscv64 linux ${{ matrix.lib_type }}
        if: github.repository_owner == 'k2-fsa' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: sherpa-onnx-*linux-riscv64*.tar.bz2

      - name: Test sherpa-onnx
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
          export QEMU_LD_PREFIX=$GITHUB_WORKSPACE/toolchain/sysroot
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/toolchain/sysroot/lib
          export QEMU_ARGS="-cpu max,vlen=256,elen=64,vext_spec=v1.0"

          ls -lh ./build-riscv64-linux-gnu-spacemit/bin

          echo "----------sherpa-onnx----------"
          qemu-riscv64 ${QEMU_ARGS} ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx --help
          readelf -d ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx

          echo "----------sherpa-onnx-offline----------"
          qemu-riscv64 ${QEMU_ARGS} ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx-offline --help
          readelf -d ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx-offline

          echo "----------sherpa-onnx-offline-tts----------"
          qemu-riscv64 ${QEMU_ARGS} ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx-offline-tts --help
          readelf -d ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx-offline-tts

      - name: Test streaming speech recognition
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
          export QEMU_LD_PREFIX=$GITHUB_WORKSPACE/toolchain/sysroot
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/toolchain/sysroot/lib
          export QEMU_ARGS="-cpu max,vlen=256,elen=64,vext_spec=v1.0"
          echo "Some mistakes in ep graph partition, disable op Gather for spacemit-ep now, will be fixed soon."
          export SPACEMIT_EP_DISABLE_OP_TYPE_FILTER="Gather"

          wget -q https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23.tar.bz2
          tar xvf sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23.tar.bz2
          rm sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23.tar.bz2

          qemu-riscv64 ${QEMU_ARGS} ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx \
            --provider=spacemit \
            --tokens=./sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23/tokens.txt \
            --encoder=./sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23/encoder-epoch-99-avg-1.onnx \
            --decoder=./sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23/decoder-epoch-99-avg-1.onnx \
            --joiner=./sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23/joiner-epoch-99-avg-1.onnx \
            ./sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23/test_wavs/0.wav

      - name: Test offline tts
        shell: bash
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
          export QEMU_LD_PREFIX=$GITHUB_WORKSPACE/toolchain/sysroot
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/toolchain/sysroot/lib
          export QEMU_ARGS="-cpu max,vlen=256,elen=64,vext_spec=v1.0"
          echo "Some mistakes in ep graph partition, disable op Gather;Cast;ConvTranspose for spacemit-ep now, will be fixed soon."
          export SPACEMIT_EP_DISABLE_OP_TYPE_FILTER="Gather;Cast;ConvTranspose"

          wget -q https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-lessac-medium.tar.bz2
          tar xf vits-piper-en_US-lessac-medium.tar.bz2
          rm vits-piper-en_US-lessac-medium.tar.bz2

          qemu-riscv64 ${QEMU_ARGS} ./build-riscv64-linux-gnu-spacemit/bin/sherpa-onnx-offline-tts \
            --provider=spacemit \
            --vits-model=./vits-piper-en_US-lessac-medium/en_US-lessac-medium.onnx \
            --vits-data-dir=./vits-piper-en_US-lessac-medium/espeak-ng-data \
            --vits-tokens=./vits-piper-en_US-lessac-medium/tokens.txt \
            --output-filename=./liliana-piper-en_US-lessac-medium.wav \
            'liliana, the most beautiful and lovely assistant of our team!'

      - uses: actions/upload-artifact@v4
        if: matrix.lib_type == 'shared'
        with:
          name: wave
          path: ./*.wav
